/**
 * ATTENTION. This code was AUTO GENERATED by ts2typebox. While I don't know
 * your use case, there is a high chance that direct changes to this file get
 * lost. Consider making changes to the underlying Typescript code you use to
 * generate this file instead. The default file is called "types.ts", perhaps
 * have a look there! :]
 */

import { Type, type Static } from '@sinclair/typebox';
import { TADPResult } from './TADPResultSchema';
import { MetaData } from './MetaDataSchema';

export type AlertSchema = Static<typeof AlertSchema>;
export const AlertSchema = Type.Object({
  evaluationID: Type.String(),
  metaData: Type.Optional(MetaData),
  status: Type.String(),
  timestamp: Type.String(),
  tadpResult: TADPResult,
});
