/**
 * ATTENTION. This code was AUTO GENERATED by ts2typebox. While I don't know
 * your use case, there is a high chance that direct changes to this file get
 * lost. Consider making changes to the underlying Typescript code you use to
 * generate this file instead. The default file is called "types.ts", perhaps
 * have a look there! :]
 */

import { Type, type Static } from '@sinclair/typebox';

export type DataCache = Static<typeof DataCache>;
export const DataCache = Type.Object({
  dbtrId: Type.Optional(Type.String()),
  cdtrId: Type.Optional(Type.String()),
  dbtrAcctId: Type.Optional(Type.String()),
  cdtrAcctId: Type.Optional(Type.String()),
  evtId: Type.Optional(Type.String()),
  creDtTm: Type.Optional(Type.String()),
  instdAmt: Type.Optional(
    Type.Object({
      amt: Type.Number(),
      ccy: Type.String(),
    }),
  ),
  intrBkSttlmAmt: Type.Optional(
    Type.Object({
      amt: Type.Number(),
      ccy: Type.String(),
    }),
  ),
  xchgRate: Type.Optional(Type.Number()),
});
