/**
 * ATTENTION. This code was AUTO GENERATED by ts2typebox. While I don't know
 * your use case, there is a high chance that direct changes to this file get
 * lost. Consider making changes to the underlying Typescript code you use to
 * generate this file instead. The default file is called "types.ts", perhaps
 * have a look there! :]
 */

import { Type, type Static } from '@sinclair/typebox';

export type AccountSchema = Static<typeof AccountSchema>;
export const AccountSchema = Type.String();

export type EntitySchema = Static<typeof EntitySchema>;
export const EntitySchema = Type.Object({
  id: Type.String(),
  creDtTm: Type.String(),
});

export type ConditionSchema = Static<typeof ConditionSchema>;
export const ConditionSchema = Type.Object({
  condId: Type.String(),
  evtTp: Type.Array(Type.String()),
  condTp: Type.String(),
  prsptv: Type.String(),
  incptnDtTm: Type.String(),
  xprtnDtTm: Type.Optional(Type.String()),
  condRsn: Type.String(),
  forceCret: Type.Boolean(),
  usr: Type.String(),
  creDtTm: Type.String(),
});

export type SchmeNm = Static<typeof SchmeNm>;
export const SchmeNm = Type.Object({
  prtry: Type.String(),
});

export type Ntty = Static<typeof Ntty>;
export const Ntty = Type.Object({
  id: Type.String(),
  schmeNm: SchmeNm,
});

export type EntityCondition = Static<typeof EntityCondition>;
export const EntityCondition = Type.Composite([
  ConditionSchema,
  Type.Object({
    ntty: Ntty,
  }),
]);

export type ClrSysMmbId = Static<typeof ClrSysMmbId>;
export const ClrSysMmbId = Type.Object({
  mmbId: Type.String(),
});

export type FinInstnId = Static<typeof FinInstnId>;
export const FinInstnId = Type.Object({
  clrSysMmbId: ClrSysMmbId,
});

export type Agt = Static<typeof Agt>;
export const Agt = Type.Object({
  finInstnId: FinInstnId,
});

export type Acct = Static<typeof Acct>;
export const Acct = Type.Composite([
  Ntty,
  Type.Object({
    agt: Agt,
  }),
]);

export type AccountCondition = Static<typeof AccountCondition>;
export const AccountCondition = Type.Composite([
  ConditionSchema,
  Type.Object({
    acct: Acct,
  }),
]);

export type EdgeSchema = Static<typeof EdgeSchema>;
export const EdgeSchema = Type.Object({
  id: Type.String(),
  source: Type.String(),
  destination: Type.String(),
  evtTp: Type.Array(Type.String()),
  incptnDtTm: Type.String(),
  xprtnDtTm: Type.Optional(Type.String()),
});
