/**
 * ATTENTION. This code was AUTO GENERATED by ts2typebox. While I don't know
 * your use case, there is a high chance that direct changes to this file get
 * lost. Consider making changes to the underlying Typescript code you use to
 * generate this file instead. The default file is called "types.ts", perhaps
 * have a look there! :]
 */

import { Type, type Static } from '@sinclair/typebox';

export type MetaData = Static<typeof MetaData>;
export const MetaData = Type.Object({
  prcgTmDp: Type.Number(),
  prcgTmED: Type.Number(),
  traceParent: Type.Optional(Type.String()),
});
