/**
 * ATTENTION. This code was AUTO GENERATED by ts2typebox. While I don't know
 * your use case, there is a high chance that direct changes to this file get
 * lost. Consider making changes to the underlying Typescript code you use to
 * generate this file instead. The default file is called "types.ts", perhaps
 * have a look there! :]
 */

import { Type, type Static } from '@sinclair/typebox';
import { DataCache } from './DataCache';

type SchmeNm = Static<typeof SchmeNm>;
const SchmeNm = Type.Object({
  Prtry: Type.String(),
});

type Othr = Static<typeof Othr>;
const Othr = Type.Object({
  Id: Type.String(),
  SchmeNm,
});

type CdtrAcctID = Static<typeof CdtrAcctID>;
const CdtrAcctID = Type.Object({
  Othr: Type.Array(Othr),
});

type Glctn = Static<typeof Glctn>;
const Glctn = Type.Object({
  Lat: Type.String(),
  Long: Type.String(),
});

type DocInitgPty = Static<typeof DocInitgPty>;
const DocInitgPty = Type.Object({
  Glctn,
});

type Doc = Static<typeof Doc>;
const Doc = Type.Object({
  Xprtn: Type.String(),
  InitgPty: DocInitgPty,
});

type Envlp = Static<typeof Envlp>;
const Envlp = Type.Object({
  Doc,
});

type SplmtryData = Static<typeof SplmtryData>;
const SplmtryData = Type.Object({
  Envlp,
});

type RmtInf = Static<typeof RmtInf>;
const RmtInf = Type.Object({
  Ustrd: Type.String(),
});

type Dtls = Static<typeof Dtls>;
const Dtls = Type.Object({
  Tp: Type.String(),
  Cd: Type.String(),
});

type RgltryRptg = Static<typeof RgltryRptg>;
const RgltryRptg = Type.Object({
  Dtls,
});

type SttlmInf = Static<typeof SttlmInf>;
const SttlmInf = Type.Object({
  SttlmMtd: Type.String(),
});

type GrpHdr = Static<typeof GrpHdr>;
const GrpHdr = Type.Object({
  MsgId: Type.String(),
  CreDtTm: Type.String(),
  NbOfTxs: Type.Number(),
  SttlmInf,
});

type PmtID = Static<typeof PmtID>;
const PmtID = Type.Object({
  InstrId: Type.String(),
  EndToEndId: Type.String(),
});

type Purp = Static<typeof Purp>;
const Purp = Type.Object({
  Cd: Type.String(),
});

type Amt = Static<typeof Amt>;
const Amt = Type.Object({
  Amt: Type.String(),
  Ccy: Type.String(),
});

type InstdAmtClass = Static<typeof InstdAmtClass>;
const InstdAmtClass = Type.Object({
  Amt,
});

type CLRSysMmbID = Static<typeof CLRSysMmbID>;
const CLRSysMmbID = Type.Object({
  MmbId: Type.String(),
});

type FinInstnID = Static<typeof FinInstnID>;
const FinInstnID = Type.Object({
  ClrSysMmbId: CLRSysMmbID,
});

type Agt = Static<typeof Agt>;
const Agt = Type.Object({
  FinInstnId: FinInstnID,
});

type ChrgsInf = Static<typeof ChrgsInf>;
const ChrgsInf = Type.Object({
  Amt,
  Agt,
});

type TrAcct = Static<typeof TrAcct>;
const TrAcct = Type.Object({
  Id: CdtrAcctID,
  Nm: Type.String(),
});

type DtAndPLCOfBirth = Static<typeof DtAndPLCOfBirth>;
const DtAndPLCOfBirth = Type.Object({
  BirthDt: Type.String(),
  CityOfBirth: Type.String(),
  CtryOfBirth: Type.String(),
});

type PrvtID = Static<typeof PrvtID>;
const PrvtID = Type.Object({
  DtAndPlcOfBirth: DtAndPLCOfBirth,
  Othr: Type.Array(Othr),
});

type CdtrID = Static<typeof CdtrID>;
const CdtrID = Type.Object({
  PrvtId: PrvtID,
});

type CtctDtls = Static<typeof CtctDtls>;
const CtctDtls = Type.Object({
  MobNb: Type.String(),
});

type Cdtr = Static<typeof Cdtr>;
const Cdtr = Type.Object({
  Nm: Type.String(),
  Id: CdtrID,
  CtctDtls,
});

type CdtTrfTxInf = Static<typeof CdtTrfTxInf>;
const CdtTrfTxInf = Type.Object({
  PmtId: PmtID,
  IntrBkSttlmAmt: InstdAmtClass,
  InstdAmt: InstdAmtClass,
  ChrgBr: Type.String(),
  XchgRate: Type.Optional(Type.Number()),
  ChrgsInf,
  InitgPty: Cdtr,
  Dbtr: Cdtr,
  DbtrAcct: TrAcct,
  DbtrAgt: Agt,
  CdtrAgt: Agt,
  Cdtr,
  CdtrAcct: TrAcct,
  Purp,
});

type FIToFICstmrCdtTrf = Static<typeof FIToFICstmrCdtTrf>;
const FIToFICstmrCdtTrf = Type.Object({
  GrpHdr,
  CdtTrfTxInf,
  RgltryRptg,
  RmtInf,
  SplmtryData,
});

export type Pacs008Schema = Static<typeof Pacs008Schema>;
export const Pacs008Schema = Type.Object({
  TxTp: Type.String(),
  FIToFICstmrCdtTrf,
  DataCache: Type.Optional(DataCache),
});
