/**
 * ATTENTION. This code was AUTO GENERATED by ts2typebox. While I don't know
 * your use case, there is a high chance that direct changes to this file get
 * lost. Consider making changes to the underlying Typescript code you use to
 * generate this file instead. The default file is called "types.ts", perhaps
 * have a look there! :]
 */

import { Type, type Static } from '@sinclair/typebox';
import { TypologyResult } from './TypologyResultSchema';

export type TADPResult = Static<typeof TADPResult>;
export const TADPResult = Type.Object({
  id: Type.String(),
  cfg: Type.String(),
  typologyResult: Type.Array(TypologyResult),
  prcgTm: Type.Optional(Type.Number()),
});
