/**
 * ATTENTION. This code was AUTO GENERATED by ts2typebox. While I don't know
 * your use case, there is a high chance that direct changes to this file get
 * lost. Consider making changes to the underlying Typescript code you use to
 * generate this file instead. The default file is called "types.ts", perhaps
 * have a look there! :]
 */

import { Type, type Static } from '@sinclair/typebox';

export type TransactionRelationshipSchema = Static<typeof TransactionRelationshipSchema>;
export const TransactionRelationshipSchema = Type.Object({
  from: Type.String(),
  to: Type.String(),
  TxTp: Type.String(),
  MsgId: Type.String(),
  CreDtTm: Type.String(),
  Amt: Type.Optional(Type.String()),
  Ccy: Type.Optional(Type.String()),
  EndToEndId: Type.String(),
  lat: Type.Optional(Type.String()),
  long: Type.Optional(Type.String()),
  TxSts: Type.Optional(Type.String()),
});
