/**
 * ATTENTION. This code was AUTO GENERATED by ts2typebox. While I don't know
 * your use case, there is a high chance that direct changes to this file get
 * lost. Consider making changes to the underlying Typescript code you use to
 * generate this file instead. The default file is called "types.ts", perhaps
 * have a look there! :]
 */

import { Type, type Static } from '@sinclair/typebox';
import { RuleResult } from './RuleResultSchema';
import { WorkFlow } from './TypologySchema';

export type TypologyResult = Static<typeof TypologyResult>;
export const TypologyResult = Type.Object({
  id: Type.String(),
  cfg: Type.String(),
  prcgTm: Type.Optional(Type.Number()),
  result: Type.Number(),
  review: Type.Optional(Type.Boolean()),
  ruleResults: Type.Array(RuleResult),
  workflow: WorkFlow,
});
